# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GamebotAPI.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GamebotAPI.proto',
  package='GamebotAPIProtocol',
  syntax='proto3',
  serialized_options=b'\252\002\025bytedance.lab.gamebot',
  serialized_pb=b'\n\x10GamebotAPI.proto\x12\x12GamebotAPIProtocol\"\xb6\x01\n\x07Request\x12>\n\x0crestart_game\x18\x01 \x01(\x0b\x32&.GamebotAPIProtocol.RequestRestartGameH\x00\x12/\n\x04step\x18\x02 \x01(\x0b\x32\x1f.GamebotAPIProtocol.RequestStepH\x00\x12/\n\x04quit\x18\x03 \x01(\x0b\x32\x1f.GamebotAPIProtocol.RequestQuitH\x00\x42\t\n\x07request\"\xbb\x01\n\x08Response\x12?\n\x0crestart_game\x18\x01 \x01(\x0b\x32\'.GamebotAPIProtocol.ResponseRestartGameH\x00\x12\x30\n\x04step\x18\x02 \x01(\x0b\x32 .GamebotAPIProtocol.ResponseStepH\x00\x12\x30\n\x04quit\x18\x03 \x01(\x0b\x32 .GamebotAPIProtocol.ResponseQuitH\x00\x42\n\n\x08response\"\r\n\x0bRequestQuit\"\x0e\n\x0cResponseQuit\"<\n\x12RequestRestartGame\x12&\n\x04init\x18\x01 \x01(\x0b\x32\x18.GamebotAPIProtocol.Init\"\x15\n\x13ResponseRestartGame\"C\n\x0bRequestStep\x12&\n\x04hero\x18\x01 \x01(\x0b\x32\x18.GamebotAPIProtocol.Hero\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\":\n\x0cResponseStep\x12*\n\x06\x61\x63tion\x18\x01 \x01(\x0b\x32\x1a.GamebotAPIProtocol.Action\"\x06\n\x04Init\"\x9f\x01\n\x04Hero\x12\n\n\x02hp\x18\x01 \x01(\x02\x12\x0e\n\x06\x65nergy\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\x12\x12\n\nrotation_x\x18\x06 \x01(\x02\x12\x12\n\nrotation_y\x18\x07 \x01(\x02\x12\x12\n\nrotation_z\x18\x08 \x01(\x02\x12\x10\n\x08ray_cast\x18\t \x03(\x02\x12\x0c\n\x04kill\x18\n \x01(\x05\"G\n\x06\x41\x63tion\x12\x0c\n\x04move\x18\x01 \x01(\x05\x12\r\n\x05shoot\x18\x02 \x01(\x08\x12\x0f\n\x07mouse_x\x18\x03 \x01(\x02\x12\x0f\n\x07mouse_y\x18\x04 \x01(\x02\x42\x18\xaa\x02\x15\x62ytedance.lab.gamebotb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='GamebotAPIProtocol.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart_game', full_name='GamebotAPIProtocol.Request.restart_game', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='GamebotAPIProtocol.Request.step', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quit', full_name='GamebotAPIProtocol.Request.quit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='GamebotAPIProtocol.Request.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=41,
  serialized_end=223,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='GamebotAPIProtocol.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='restart_game', full_name='GamebotAPIProtocol.Response.restart_game', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='GamebotAPIProtocol.Response.step', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quit', full_name='GamebotAPIProtocol.Response.quit', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='GamebotAPIProtocol.Response.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=226,
  serialized_end=413,
)


_REQUESTQUIT = _descriptor.Descriptor(
  name='RequestQuit',
  full_name='GamebotAPIProtocol.RequestQuit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=428,
)


_RESPONSEQUIT = _descriptor.Descriptor(
  name='ResponseQuit',
  full_name='GamebotAPIProtocol.ResponseQuit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=444,
)


_REQUESTRESTARTGAME = _descriptor.Descriptor(
  name='RequestRestartGame',
  full_name='GamebotAPIProtocol.RequestRestartGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='GamebotAPIProtocol.RequestRestartGame.init', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=506,
)


_RESPONSERESTARTGAME = _descriptor.Descriptor(
  name='ResponseRestartGame',
  full_name='GamebotAPIProtocol.ResponseRestartGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=529,
)


_REQUESTSTEP = _descriptor.Descriptor(
  name='RequestStep',
  full_name='GamebotAPIProtocol.RequestStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hero', full_name='GamebotAPIProtocol.RequestStep.hero', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='GamebotAPIProtocol.RequestStep.done', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=598,
)


_RESPONSESTEP = _descriptor.Descriptor(
  name='ResponseStep',
  full_name='GamebotAPIProtocol.ResponseStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='GamebotAPIProtocol.ResponseStep.action', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=658,
)


_INIT = _descriptor.Descriptor(
  name='Init',
  full_name='GamebotAPIProtocol.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=666,
)


_HERO = _descriptor.Descriptor(
  name='Hero',
  full_name='GamebotAPIProtocol.Hero',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hp', full_name='GamebotAPIProtocol.Hero.hp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy', full_name='GamebotAPIProtocol.Hero.energy', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='GamebotAPIProtocol.Hero.x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='GamebotAPIProtocol.Hero.y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='GamebotAPIProtocol.Hero.z', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_x', full_name='GamebotAPIProtocol.Hero.rotation_x', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_y', full_name='GamebotAPIProtocol.Hero.rotation_y', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_z', full_name='GamebotAPIProtocol.Hero.rotation_z', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ray_cast', full_name='GamebotAPIProtocol.Hero.ray_cast', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kill', full_name='GamebotAPIProtocol.Hero.kill', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=828,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='GamebotAPIProtocol.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='move', full_name='GamebotAPIProtocol.Action.move', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shoot', full_name='GamebotAPIProtocol.Action.shoot', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mouse_x', full_name='GamebotAPIProtocol.Action.mouse_x', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mouse_y', full_name='GamebotAPIProtocol.Action.mouse_y', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=901,
)

_REQUEST.fields_by_name['restart_game'].message_type = _REQUESTRESTARTGAME
_REQUEST.fields_by_name['step'].message_type = _REQUESTSTEP
_REQUEST.fields_by_name['quit'].message_type = _REQUESTQUIT
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['restart_game'])
_REQUEST.fields_by_name['restart_game'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['step'])
_REQUEST.fields_by_name['step'].containing_oneof = _REQUEST.oneofs_by_name['request']
_REQUEST.oneofs_by_name['request'].fields.append(
  _REQUEST.fields_by_name['quit'])
_REQUEST.fields_by_name['quit'].containing_oneof = _REQUEST.oneofs_by_name['request']
_RESPONSE.fields_by_name['restart_game'].message_type = _RESPONSERESTARTGAME
_RESPONSE.fields_by_name['step'].message_type = _RESPONSESTEP
_RESPONSE.fields_by_name['quit'].message_type = _RESPONSEQUIT
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['restart_game'])
_RESPONSE.fields_by_name['restart_game'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['step'])
_RESPONSE.fields_by_name['step'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['quit'])
_RESPONSE.fields_by_name['quit'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_REQUESTRESTARTGAME.fields_by_name['init'].message_type = _INIT
_REQUESTSTEP.fields_by_name['hero'].message_type = _HERO
_RESPONSESTEP.fields_by_name['action'].message_type = _ACTION
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['RequestQuit'] = _REQUESTQUIT
DESCRIPTOR.message_types_by_name['ResponseQuit'] = _RESPONSEQUIT
DESCRIPTOR.message_types_by_name['RequestRestartGame'] = _REQUESTRESTARTGAME
DESCRIPTOR.message_types_by_name['ResponseRestartGame'] = _RESPONSERESTARTGAME
DESCRIPTOR.message_types_by_name['RequestStep'] = _REQUESTSTEP
DESCRIPTOR.message_types_by_name['ResponseStep'] = _RESPONSESTEP
DESCRIPTOR.message_types_by_name['Init'] = _INIT
DESCRIPTOR.message_types_by_name['Hero'] = _HERO
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.Response)
  })
_sym_db.RegisterMessage(Response)

RequestQuit = _reflection.GeneratedProtocolMessageType('RequestQuit', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTQUIT,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.RequestQuit)
  })
_sym_db.RegisterMessage(RequestQuit)

ResponseQuit = _reflection.GeneratedProtocolMessageType('ResponseQuit', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEQUIT,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.ResponseQuit)
  })
_sym_db.RegisterMessage(ResponseQuit)

RequestRestartGame = _reflection.GeneratedProtocolMessageType('RequestRestartGame', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTRESTARTGAME,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.RequestRestartGame)
  })
_sym_db.RegisterMessage(RequestRestartGame)

ResponseRestartGame = _reflection.GeneratedProtocolMessageType('ResponseRestartGame', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSERESTARTGAME,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.ResponseRestartGame)
  })
_sym_db.RegisterMessage(ResponseRestartGame)

RequestStep = _reflection.GeneratedProtocolMessageType('RequestStep', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTEP,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.RequestStep)
  })
_sym_db.RegisterMessage(RequestStep)

ResponseStep = _reflection.GeneratedProtocolMessageType('ResponseStep', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSESTEP,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.ResponseStep)
  })
_sym_db.RegisterMessage(ResponseStep)

Init = _reflection.GeneratedProtocolMessageType('Init', (_message.Message,), {
  'DESCRIPTOR' : _INIT,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.Init)
  })
_sym_db.RegisterMessage(Init)

Hero = _reflection.GeneratedProtocolMessageType('Hero', (_message.Message,), {
  'DESCRIPTOR' : _HERO,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.Hero)
  })
_sym_db.RegisterMessage(Hero)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'GamebotAPI_pb2'
  # @@protoc_insertion_point(class_scope:GamebotAPIProtocol.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
